### ISSUE TITLE
What is the purpose of this repo ?

### ISSUE THREAD

**Issue by paolomainardi** [Sylius/SyliusShopApiPlugin#166]
Hey guys, we are considering to use Sylius for building a store/ecommerce api and i've just discovered this repo.
Could you clarify the scope of this project ?

Thanks!

**Comment by pjedrzejewski** [comment]
@paolomainardi It provides API used for building shop frontend with Vue.js/React/AngularJS and any other framework. We hope to announce this plugin properly in the coming days with a blog post explaining. We currently use it for one project that uses Vue.js for the storefront. :)

**Comment by paolomainardi** [comment]
@pjedrzejewski great, we were looking to use sylius.org to do that, so we are waiting your public announce, thanks a lot guys!

**Comment by pjedrzejewski** [comment]
@paolomainardi I will close this issue then. :)
