### ISSUE TITLE
As an API Client, I want to authenticate with JWT

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/SyliusShopApiPlugin#2]
https://github.com/lexik/LexikJWTAuthenticationBundle

**Comment by lchrusciel** [comment]
This task will be postponed. Alpha1 is ready to be tagged. /cc @pjedrzejewski

**Comment by pjedrzejewski** [comment]
@lchrusciel Go ahead! ;) I will change the milestone.

**Comment by lchrusciel** [comment]
@pjedrzejewski I would like to include #44 and #42 to alpha1. Can you merge these PR's, or should I do it?
