### ISSUE TITLE
cart total price and item price not match

### ISSUE THREAD

**Issue by sdleiw** [Sylius/SyliusShopApiPlugin#228]
Hi,
I have added an item in the cart by the post API /carts/{token}/items, it worked with a 201 response, but when I try to fetch the cart by a GET /carts/{token}, the price seemed to be wrong, I have unit price 808 and quantity 1, but got a total of 469, did I miss something here?
<img width="592" alt="bildschirmfoto 2017-10-19 um 22 05 32" src="https://user-images.githubusercontent.com/32791659/31792021-e6ed6e86-b51a-11e7-829a-50ab6c6cff8f.png">

have tried with other products, and have similar problem

**Comment by lchrusciel** [comment]
Can you check if any promotion has been applied?

**Comment by sdleiw** [comment]
hi @lchrusciel 

I think you are right, have noticed that some other calculations in the cart were applied, I'll check the cart again, 

I have another general question here, is there some kind of sylius forum or chat channel available? I have some problems during development and want to discuss with someone, but just found a google user group which is also not so active.

**Comment by lchrusciel** [comment]
@sdleiw the best option would be to join us on our slack channel. Please follow this doc http://docs.sylius.org/en/latest/support/index.html#slack

**Comment by sdleiw** [comment]
there is a Christmas discount applied to my cart, so the price calculation is ok, this issue can be closed
