### ISSUE TITLE
Cannot add item to cart - quantity seems to be converted to string

### ISSUE THREAD

**Issue by ce-bo** [Sylius/SyliusShopApiPlugin#235]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Version            | v1.0.0-beta.20

I try to add a simple item to my cart but i receive an error:
`{"code":400,"message":"Validation failed","errors":{"quantity":["sylius.shop_api.quantity.type_integer"]}}`

Request URL:
`/shop-api/carts/CART_TOKEN/items`

My request params:
`{
            quantity: 2,
            productCode: "46",
            variantCode: "47"
        }`

In the profiler of my Sylius application I can see that the quantity is converted to a string (this could be the problem).
![grafik](https://user-images.githubusercontent.com/26900540/32330757-62349c10-bfe1-11e7-9678-72fb06604044.png)

Any solutions for this?

Thank you!

**Comment by lchrusciel** [comment]
Probably it would require a turn of the validation and maybe some integer cast. Are you willing to open a PR?

**Comment by sdleiw** [comment]
@ce-bo, I had the same problem when sending post payload with Formdata, integer will be automatically converted to string, using plain object works for me.

**Comment by lchrusciel** [comment]
but I think it would be more convenient to just cast it to an integer in a controller. Should be rather a simple change. I'm wondering if it wouldn't be enough to just change `$request->request->get('quantity')` to `$request->request->getInt('quantity')` in https://github.com/Sylius/SyliusShopApiPlugin/blob/master/src/Request/PutSimpleItemToCartRequest.php#L41 and correspond methods. Or change in validation and just casting the value in command constructor.

**Comment by ce-bo** [comment]
@lchrusciel, I agree with your suggestion.
I already tested it for all relevant requests and it works fine for me. 

Unfortunately I'm not able to open a PR in the moment. Can you do this, please?
Thank you!
