### ISSUE TITLE
[RFC] PriceViewFactoryInterface tightly coupled to default model 

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/SyliusShopApiPlugin#258]
Hi, 

RFC / Suggestion. I'm trying to override the price read model to use our custom price calculator. The PriceViewFactory just receives price and currency, and therefore no context is given to generate or alter the price.

I suggest the following API for PriceViewFactoryInterface: 

`public function create(ProductVariantInterface $variant, ChannelInterface $channel) : PriceView`

I can send a PR if you agree. Will break BC (obviously).

P.D. Really useful plugin BTW. Congrats!

**Comment by gorkalaucirica** [comment]
Can't be done, it's also linked to models not related to products

**Comment by lchrusciel** [comment]
The main concern of price view factory is to provide a coherent structure of price in any object. This logic should be placed in one of product factories or brand new product price view factory which will use regular price view factory. 

Sorry for long response time but I'm overloaded with work atm. 

Anyway, I'm glad you liked our plugin ;)

**Comment by gorkalaucirica** [comment]
@lchrusciel I was thinking about creating a ProductPriceView class. I think this can make sense, because right now original price is not serialized for example, and depending the use case you may want to show it.

WDYT?

**Comment by lchrusciel** [comment]
It can be useful, but the problem is that we need to provide a common structure with the regular price... Not sure if we should duplicate this logic or decorate PriceViewFactory.

If you find some free time, then sure, we can add it.

**Comment by gorkalaucirica** [comment]
ProductPriceView can make use of PriceViewFactory to serialize the prices (originalPrice and price).

I will give it a try
