### ISSUE TITLE
No route found for /shop-api/login_check.

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [Sylius/SyliusShopApiPlugin#283]
No route found for /shop-api/login_check. Help

**Comment by benjaminzhou01** [comment]
> No route found for /shop-api/login_check. Help

Help

**Comment by Zales0123** [comment]
Hello @benjaminzhou01, as it's said in plugin readme, [by default no authorization is provided together with this bundle](https://github.com/Sylius/ShopApiPlugin#authorization). You must configure it manually :)
