### ISSUE TITLE
Can't be installed with sylius 1.12

### ISSUE THREAD

**Issue by avasiliauskas** [Sylius/SyliusShopApiPlugin#733]
ShopApiPlugin requires "symfony/messenger": "^4.4|^5.2" but Sylius 1.12 requires "symfony/messenger": "^5.4"

If there is no plans to support Sylius 1.12 version should be stricted to ^1.10.0 in composer.json

**Comment by diimpp** [comment]
It's just behind on maintenance, there is no big difference between 1.10 and 1.12 aside new api changes.

So if this plugin requires ^5.2 and sylius ^5.4 then messenger 5.4 satisfies both requirements?

^1.10.0 will be the same as ^1.10 as this is stable release and not [pre-release](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)

What kind of error you're getting? Are you on messenger 4.4 by any chance?

**Comment by mamazu** [comment]
Yeah just tried it with 1.13 as well and it works. Maybe you need to install the plugin with some extra composer flags:
```
composer require sylius/shop-api-plugin --update-with-all-dependencies 
```
This will also run a package upgrades. And if that doesn't help you might want to delete the `vendor` directory and the `composer.lock` file and install it completely from scratch. (But you should check the package changes in the version control very carefully.

**Comment by avasiliauskas** [comment]
Thanks, closing issue, it seems there was my fault.
